version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-stretch-browsers
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:2-stretch-browsers
    steps:
      - checkout
      - run: nosetests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
