version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-stretch-browsers
    steps:
      - run: virtualenv venv
      - run: . venv/bin/activate
      - run: pip install nose==1.3.7
      - run: nosetests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
